# Generated by Django 4.1.7 on 2023-03-06 14:56

import api.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exp_date', models.DateField(validators=[api.models.validate_exp_date])),
                ('holder', models.CharField(max_length=255, validators=[api.models.validate_holder])),
                ('number', models.CharField(max_length=16, validators=[api.models.validate_number])),
                ('cvv', models.CharField(blank=True, max_length=4, null=True, validators=[api.models.validate_cvv])),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
